model: SASRec

# model args
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'BPR'

learning_rate: 7e-3
learner: sgd
epochs: 100

# data args
data_source: up

# save_dataset: True
# save_dataloaders: True
load_col:
    # inter: [user_id, item_id, exposure_time, item_type_recommend]
    inter: [user_id, item_id, exposure_time]
unused_col:
    # inter: [exposure_time, exposure_time_list, item_type_recommend, item_type_recommend_list]
    inter: [exposure_time, exposure_time_list]

# eval args
eval_args:
  split: {'LS': 'test_only'}
  order: TO
  mode: full
eval_batch_size: 4096