model: SASRecFeat

# model args
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'BPR'
item_feat_emb: 'pth/changsha-item_img_emb.pth'

# data args
task_fields: ['user_id']
data_source: up

learning_rate: 3e-3
num_local_update: 5
local_learner: sgd
local_learning_rate: 0.001
local_weight_decay: 0.0
# local_modules: ['item_embedding']
# local_modules: ['item_embedding', 'position_embedding', 'trm_encoder', 'LayerNorm']
local_modules: ['position_embedding', 'trm_encoder', 'LayerNorm']

meta_epochs: 10
stopping_step: 500

# save_dataset: True
# save_dataloaders: True
load_col:
    # inter: [user_id, item_id, exposure_time, item_type_recommend]
    inter: [user_id, item_id, exposure_time]
unused_col:
    # inter: [exposure_time, exposure_time_list, item_type_recommend, item_type_recommend_list]
    inter: [exposure_time, exposure_time_list]

# eval args
eval_batch_size: 4096